var fs = require('fs')
var sortMembers = require('../lib/sort.js')
var members = require('./data/members.json')
var expected = require('./data/expected.json')
var deps = require('./data/deps.json')
var members2 = require('./data/members2.json')
var expected2 = require('./data/expected2.json')
var deps2 = require('./data/deps2.json')
var members3 = require('./data/members3.json')
var expected3 = require('./data/expected3.json')
var deps3 = require('./data/deps3.json')
var test = require('tape')

test('sort', function (t) {
  t.plan(3)
  t.deepEquals(sortMembers(members, deps, 9064715), expected)
  t.deepEquals(sortMembers(members2, deps2, 9099828), expected2)
  t.deepEquals(sortMembers(members3, deps3, 9100599), expected3)
})
